module.exports = {
  apps: [
    {
      name: 'subbly-dev',
      script: 'bash',
      args: '-c "rm -rf .next && pnpm run dev"',
      cwd: '/project/workspace/main',
      interpreter: 'none',
      autorestart: true,
      exp_backoff_restart_delay: 1000,
      log_file: '/project/workspace/.subbly/logs/output.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DDTHH:mm:ss.SSS',
      instances: 1,
      env: {
        FORCE_COLOR: '1',
        TERM: 'xterm-256color',
      },
    },
    {
      name: 'css-watcher',
      script: 'chokidar',
      args: '"src/**/*.css" "src/**/*.scss" --ignore "**/node_modules/**" --ignore "**/.next/**" --ignore "**/.git/**" --ignore "**/.subbly/**" --debounce 1000 -c "rm -rf .next && pm2 restart subbly-dev"',
      cwd: '/project/workspace/main',
      autorestart: true,
      interpreter: 'none',
      log_file: '/project/workspace/.subbly/logs/css-watcher.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DDTHH:mm:ss.SSS',
      env: {
        SHELL: '/bin/bash',
      },
    },
    {
      name: 'deps-watcher',
      script: 'chokidar',
      args: '"pnpm-lock.yaml" "package.json" --polling --poll-interval 500 --debounce 1000 -c "pnpm install --dangerously-allow-all-builds && pm2 restart subbly-dev"',
      cwd: '/project/workspace/main',
      autorestart: true,
      interpreter: 'none',
      log_file: '/project/workspace/.subbly/logs/deps-watcher.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DDTHH:mm:ss.SSS',
      env: {
        CI: 'true',
        SHELL: '/bin/bash',
      },
    },
  ],
}
