import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { TransitionRouterProvider } from '@/lib/transition-router/transition-router-provider'
import { SubblyScript } from '@/lib/subbly/subbly-script'
import Script from 'next/script'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Subbly',
  description: 'Generated by Subbly AI',
}

//Never remove this.
export const revalidate = 600

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {process.env.NEXT_PUBLIC_SUBBLY_API_KEY && (
            <SubblyScript
              apiKey={process.env.NEXT_PUBLIC_SUBBLY_API_KEY}
            />
          )}
          <div className="flex min-h-screen flex-col">
            <div className="relative flex-grow h-full">
              <TransitionRouterProvider>{children}</TransitionRouterProvider>
            </div>
          </div>
        </Providers>
        <Script
          id="sandbox-messenger"
          src="https://assets.subbly.co/builder/sandbox-messenger.js"
          type="module"
          strategy="afterInteractive"
        />
      </body>
    </html>
  )
}
