import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { TransitionRouterProvider } from '@/lib/transition-router/transition-router-provider'
import { SubblyScript } from '@/lib/subbly/subbly-script'
import { getLocale } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Subbly',
  description: 'Generated by Subbly AI',
}

//Never remove this.
export const revalidate = 600

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
        <Providers>
          {process.env.NEXT_PUBLIC_SUBBLY_API_KEY && (
            <SubblyScript
              apiKey={process.env.NEXT_PUBLIC_SUBBLY_API_KEY}
            />
          )}
          <div className="flex min-h-screen flex-col">
            <div className="relative flex-grow h-full">
              <NextIntlClientProvider>
                <TransitionRouterProvider>{children}</TransitionRouterProvider>
              </NextIntlClientProvider>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
